config/routes.rb
Rails.application.routes.draw do
  get '/', :to => 'default#index', as: 'index'
  get '/goodbye', :to => 'default#goodbye', as: 'goodbye'

  root 'default#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  def index
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/views/default/goodbye.html.erb
<h1 class="text-center display-1">goodbye, world!</h1>

app/views/default/index.html.erb
<h1 class="display-1 text-center">
  привіт світ
</h1>
<h1 class="display-3 text-center"><%= link_to 'до побачення', goodbye_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uebung2</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="h-100">
<div class="container w-100 h-100">
  <%= yield %>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>
</html>